version: "3.8"

services:
  igdb:
    ports:
      - 6969
    build:
      target: prod
    restart: always
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.echat-server.rule=Host(`igdb.myngz.com`)'
      - 'traefik.http.routers.echat-server.entrypoints=websecure'
      - 'traefik.http.routers.echat-server.tls.certresolver=letsencrypt'
      - 'traefik.http.services.echat-server.loadbalancer.server.port=6969'

networks:
  proxy:
    external: false
    name: proxy
