version: "3.8"

services:
  igdb:
    container_name: igdb
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: always
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.igdb.rule=Host(`igdb.myngz.com`)'
      - 'traefik.http.routers.igdb.entrypoints=websecure'
      - 'traefik.http.routers.igdb.tls.certresolver=letsencrypt'
      - 'traefik.http.services.igdb.loadbalancer.server.port=6969'

networks:
  proxy:
    external: false
    name: proxy
