name: Docker Prod

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env
          echo CLIENT_ID=${{ secrets.DATABASE_URL }} >> .env
          echo CLIENT_SECRET=${{ secrets.SERVER_PORT }} >> .env
          cat .env

      - name: Docker run
        run: docker-compose up -d --force-recreate --build
