name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
          echo DOMAIN=${{ secrets.DOMAIN }} >> .env
          cat .env

      - name: Docker run
        run: docker compose up -d --force-recreate --build
